language: node_js
sudo: false
node_js:
  - '0.12'
  - '0.10'
  - iojs

branches:
  only:
    - master
    - develop
    - /^release-.*$/

before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install

script:
  - gulp

matrix:
  allow_failures:
    - node_js: iojs

notifications:
  email:
    - joho@joho.io
